port: 4001

title: Rob Koch
url: 'http://robko.ch'
# baseurl: 'http://robko.ch/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
# style: styles-3
# style: styles-4
# style: styles-5
style: styles-6

# removes images, moves skills to sidebar (more printer friendly)
light: true

#Profile information
name: Rob Koch
tagline: Software Engineer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: kochrt@gmail.com
phone: 513-593-5938
website: kochrt.github.com #do not add http://
linkedin: kochrt
github: kochrt
pdf: resume.pdf
#Update all the sections by editing the files inside _includes folder.

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge